export class Sintomas {
    idConsulta:number;
    dateConsulta:string;
    breathingProblem:string;
    fever:string;
    dryCough:string;
    soreThroat:string;
    runningSe:string;
    asthma:string;
    chronicLungDisease:string;
    headache:string;
    heartDisease:string;
    diabetes:string;
    hyperTension:string;
    fatigue:string;
    gastrointestinal:string;
    abroadTravel:string;
    contactWithCovidPatient:string;
    attendedLargeGathering:string;
    visitedPublicExposedPlaces:string;
    familyWorkingInPublicExposedPlaces:string;
    wearingMasks:string;
    sanitizationFromMarket:string;
    covid:string;
}
